config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  get 'analysis/index'
  get 'analysis/positive'
  get 'analysis/negative'
  
  root to: 'things#index'
 
   get 'signup', to: 'users#new'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

 
 resources :things
 resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
    belongs_to :user
    
    validates :name, presence: true, length: {maximum: 255 }
    validates :date, presence: true
    validates :shop, presence: true
    validates :highprice, presence: true
    validates :lowprice, presence: true
    
    def save_price
        if self.shop == "super"
            self.lowprice
        else
            self.highprice
        end
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :things
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :classed_things, only: [:positive, :negative]

  
  def index
  end
  
  def positive
  end
  
  def negative
  end
  
  private
  
  def classed_things
    @things = current_user.things
    @super_things = @things.where(shop: 'super')
    @conveni_things = @things.where(shop: 'conveni')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include SessionsHelper

private

def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to controller: :things, astion: :index
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @things = current_user.things
    @super_things = @things.where(shop: 'super')
    @conveni_things = @things.where(shop: 'conveni')
  end
  
  def show
  end
  
  def new
    @thing = Thing.new
  end
  
  def create
    @thing = current_user.things.build(adjust_attributes)
    if @thing.save
      flash[:success] = '記録完了！'
      redirect_to @thing
    else
      flash.now[:danger] = '記録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @thing.update(adjust_attributes)
      flash[:success] = '商品が編集されました。'
      redirect_to @thing
    else
      flash.now[:danger] = '商品の編集に失敗しました。'
      render :edit
    end
  end
  
  def destroy
    @thing.destroy
    
    flash[:success] = '商品を消去しました。'
    redirect_to things_url
  end

  private
  
  def set_thing
    @thing = Thing.find(params[:id])
  end
  
  def thing_params
    params.require(:thing).permit(:name, :price, :date, :shop)
  end
  
  def adjust_attributes
    attrs = thing_params
    
    # attrs[:price].present? +> false なら弾く
    
    if attrs[:shop] == 'super'
      # lowprice に price の内容そのまま、highprice に加工した値段をセット
      # attrs の lowprice キーに price の値を入れる
      attrs[:lowprice] = attrs[:price].to_i
      # attrs の highprice キーに price * 1.3 の値を入れる
      attrs[:highprice] = attrs[:price].to_i*1.3
    else
      # highprice に price の内容そのまま、lowprice に加工した値段をセット
      # 上記の逆パターン
      attrs[:highprice] = attrs[:price].to_i
      attrs[:lowprice] = attrs[:price].to_i*0.7
    end
    # attrs から :price キーを削除
    attrs.delete(:price)
    # 戻り値の希望
    return attrs
    # {name: '名前', lowprice: "1000", highprice: "1200", date: "2020-10-1", shop: "super"}
  end
  
  def correct_user
    @thing = current_user.things.find_by(id: params[:id])
    unless @thing
      redirect_to root_url
    end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to controller: :things, action: :index
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/things_helper.rb
module ThingsHelper
    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/analysis/index.html.erb
<h1>分析ページ</h1>

<p><%= link_to 'スーパーで買ったものをコンビニで買っていたら',  analysis_positive_path %></P>
<p><%= link_to 'コンビニで買ったものをスーパーで買っていたら', analysis_negative_path %></p>

<button type="button" class="btn btn-outline-primary"><%= link_to '一覧に戻る', things_path %></button>

app/views/analysis/negative.html.erb
<p>もしコンビニで買ったものをスーパーで買っていたら</p>
<p>合計<%= @conveni_things.sum(:lowprice) %>円でした。</p>

<p>コンビニで購入した金額が<%= @conveni_things.sum(:highprice) %> 円だったので</p>
<p>あなたは<%= @conveni_things.sum(:highprice) - @conveni_things.sum(:lowprice) %>円損しました。</p>
<p>コンビニはなるべく使わないようにしましょう。</p>

<%= link_to '戻る', analysis_index_path %>
<%= link_to '浪費一覧', things_path %>

app/views/analysis/positive.html.erb
<p>もしスーパーで買ったものをコンビニで買っていたら</p>

<p>合計<%= @super_things.sum(:highprice) %>円でした。</p>　

<p>スーパーで購入した合計金額が<%= @super_things.sum(:lowprice) %> 円だったので</p>

<p><%= @super_things.sum(:highprice) - @super_things.sum(:lowprice) %>円の節約に成功しました！！</p>
<p>このまま頑張りましょう！</p>

<%= link_to '戻る', analysis_index_path %>
<%= link_to '浪費一覧', things_path %>

app/views/layouts/_error messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Rouhi</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
          <li class="nav-item"><%= link_to '分析', analysis_index_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '商品登録', new_thing_path, class: 'nav-link' %></li>
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rouhi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_with(model: thing, local: true) do |f| %>
<% if thing.errors.any? %>
  <div id="error_explanation">
   <ul>
    <% thing.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
<% end %>
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name %>
  
  <%= f.label :price, '値段' %>
  <% if action_name == "new" %>
    <%= f.number_field :price, step: 1, value: 0 %>
  <% elsif action_name == "edit" || action_name == "update" %>
    <%= f.number_field :price, step: 1, value: f.object.save_price %>
  <% elsif action_name == "create" %>
    <%= f.number_field :price, step: 1, value: params[:thing][:price] %>
  <% end %>
  
  <%= f.label :date, '日付' %>
  <%= f.date_select :date %>
  

  <%= f.radio_button :shop, :super %>
  <%= f.label :shop, "スーパー", {value: :super, style: "display: inline-block;"} %>
  <%= f.radio_button :shop, :conveni %>
  <%= f.label :shop, "コンビニ", {value: :conveni, style: "display: inline-block;"} %>


  <%= f.submit '投稿' %>
<% end %>

app/views/things/edit.html.erb
<h1>商品編集ページ</h1>

<%= render 'form', thing: @thing %>

<%= link_to '一覧に戻る', things_path %>

app/views/things/index.html.erb
<h1>浪費一覧</h1>
<table class="table">
  <tr>
    <th class="text-center">商品名</th>
    <th class="text-center">日付</th>
    <th class="text-center">お店</th>
    <th class="text-center">値段</th>
  </tr>
    <% @things.each do |thing| %>
    <tr>
  　   <td><%= link_to thing.name, thing %></td>
      <td class="text-right"><%= thing.date %></td>
    　  <% if thing.shop == 'super' %>
       　<td class="text-right">スーパー</td>
       　<td class="text-right"><%= thing.lowprice %>円</td>
      　<% else %>
      　 <td class="text-right">コンビニ</td>
    　  　<td class="text-right"><%= thing.highprice %>円</td>
    　  <% end %>
  　<% end %>
　</tr>
</table>

<h2>スーパーの合計とコンビニの合計</h2>


<p>スーパー合計: <%= @super_things.sum(:lowprice) %>円</p>
<p>コンビニ合計: <%= @conveni_things.sum(:highprice) %>円</p>

app/views/things/new.html.erb
<h1>商品登録ページ</h1>

<%= render 'form', thing: @thing %>

<%= link_to '一覧に戻る', things_path %>

app/views/things/show.html.erb
<table class="table">
  <tr>
    <th class="text-center">商品名</th>
    <th class="text-center">日付</th>
    <th class="text-center">お店</th>
    <th class="text-center">値段</th>
  </tr>
  <tr>
  　<td><%= @thing.name %></td>
    <td class="text-right"><%= @thing.date %></td>
    　<% if @thing.shop == 'super' %>
     　<td class="text-right">スーパー</td>
     　<td class="text-right"><%= @thing.lowprice %>円</td>
    　<% else %>
    　　<td class="text-right">コンビニ</td>
    　　<td class="text-right"><%= @thing.highprice %>円</td>
  　　<% end %>
　</tr>
</table>

<button type="button" class="btn btn-outline-primary"><%= link_to '一覧に戻る', things_path %></button>
<button type="button" class="btn btn-outline-success"><%= link_to '編集', edit_thing_path(@thing) %></button>
<button type="button" class="btn btn-outline-danger"><%= link_to '消去', @thing, method: :delete, data: {confirm: '本当に削除してもよろしいですか'} %></button>

app/views/users/new.html.erb
<h1>ユーザー登録ページ</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>
  
  <%= f.label :email, 'Email' %>
  <%= f.email_field :email %>
  
  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit 'Sign up' %>
<% end %>